name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter_train_2025:
    path: ../
  flutter:
    sdk: flutter
  widgetbook: ^3.14.2
  widgetbook_annotation: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.13.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
